version: '3'

services:

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static/
    command: cp -r /app/collected_static/. /backend_static/static/

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  nginx:
    build: ./nginx_dev/
    env_file: .env
    volumes:
      - static:/backend_static/
      - ./backend/media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    network_mode: host
    depends_on:
      - frontend

volumes:
  static: